version: 1.0.{build}

image: Ubuntu

services:
  - docker

# dockerhub credentials encrypted using https://ci.appveyor.com/tools/encrypt
environment:
  DOCKERHUB_USERNAME:
    secure: nskdOtzA4S9nz1hvoQxjUQ==
  DOCKERHUB_PASSWORD:
    secure: Lxha1UhmqVrk3r8AVe3UZw==
  DOCKERHUB_REPO_TENANTS: micro.services.tenants
  DOCKERHUB_REPO_CONTENT: micro.services.content

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# install docker compsose
install: 
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker version


# build the containers
build_script:
  - sh: docker-compose -f docker-compose.yml build

# run all test scenarios
test_script:  
  - sh: docker-compose -f docker-compose-tests-unit-tenants.yml up --build --force-recreate
  - sh: docker-compose -f docker-compose-tests-unit-content.yml up --build --force-recreate
  - sh: docker-compose -f docker-compose-tests-integration-tenants.yml up --build --force-recreate --exit-code-from micro.services.tenants.integrationtests --abort-on-container-exit
  - sh: docker-compose -f docker-compose-tests-integration-content.yml up --build --force-recreate --exit-code-from micro.services.content.integrationtests --abort-on-container-exit
  - sh: docker-compose -f docker-compose-tests-acceptance.yml up --build --force-recreate --exit-code-from micro.acceptancetests --abort-on-container-exit

# find test output files and post to appveyor api
# note the format is mstest and the files were generated using `dotnet test --logger trx
# https://www.appveyor.com/docs/running-tests/
after_test:
  - sh: find tests -type f -name '*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID"

# login to dockerhub and tag containers
before_deploy:
  - sh: docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
  - sh: docker tag $DOCKERHUB_REPO_TENANTS $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_TENANTS:$APPVEYOR_BUILD_NUMBER
  - sh: docker tag $DOCKERHUB_REPO_TENANTS $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_TENANTS:latest
  - sh: docker tag $DOCKERHUB_REPO_CONTENT $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_CONTENT:$APPVEYOR_BUILD_NUMBER
  - sh: docker tag $DOCKERHUB_REPO_CONTENT $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_CONTENT:latest

# tag and push all containers
deploy_script:
  - sh: docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_TENANTS
  - sh: docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_CONTENT

artifacts:
  - path: '/tests/*.xml'







