version: 1.0.{build}

image: Ubuntu

services:
  - docker
  
install: 
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
  - sudo chmod +x /usr/local/bin/docker-compose

before_build:
  - sh: echo "%DOCKER_PASSWORD" | docker login -u="%DOCKER_USERNAME" --password-stdin

build_script:
  - sh: docker-compose -f docker-compose.yml build

test_script:  
  - sh: docker-compose -f docker-compose-tests-unit-tenants.yml up --build --force-recreate
  - sh: docker-compose -f docker-compose-tests-unit-content.yml up --build --force-recreate
  - sh: docker-compose -f docker-compose-tests-integration-tenants.yml up --build --force-recreate --exit-code-from micro.services.tenants.integrationtests --abort-on-container-exit
  - sh: docker-compose -f docker-compose-tests-integration-content.yml up --build --force-recreate --exit-code-from micro.services.content.integrationtests --abort-on-container-exit
  - sh: docker-compose -f docker-compose-tests-acceptance.yml up --build --force-recreate --exit-code-from micro.acceptancetests --abort-on-container-exit

after_test:
  - sh: find tests -type f -name '*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID"

deploy_script:
  - sh: docker tag micro.services.tenants peterkneale/micro.services.tenants:latest
  - sh: docker tag micro.services.content peterkneale/micro.services.content:latest
  - sh: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - sh: docker push peterkneale/micro.services.tenants:latest
  - sh: docker push peterkneale/micro.services.content:latest

artifacts:
  - path: '/tests/*.xml'







