version: 1.0.{build}
image: Ubuntu
services:
- docker
install: 
- sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
- sudo chmod +x /usr/local/bin/docker-compose 
build_script:
- sh: docker-compose -f docker-compose.yml build
- sh: docker-compose -f docker-compose-tests-unit-tenants.yml up --build --force-recreate
- sh: docker-compose -f docker-compose-tests-unit-content.yml up --build --force-recreate
- sh: docker-compose -f docker-compose-tests-integration-tenants.yml up --build --force-recreate --exit-code-from micro.services.tenants.integrationtests --abort-on-container-exit
- sh: docker-compose -f docker-compose-tests-integration-content.yml up --build --force-recreate --exit-code-from micro.services.content.integrationtests --abort-on-container-exit
- sh: docker-compose -f docker-compose-tests-acceptance.yml up --build --force-recreate --exit-code-from micro.services.acceptancetests --abort-on-container-exit

artifacts:
    - path: '/tests/*.xml'