version: '3.4'

services:

  micro.acceptancetests:
    image: micro.acceptancetests
    build:
      context: .
      dockerfile: tests/Micro.AcceptanceTests/Dockerfile    
    depends_on:
      - micro.services.tenants
      - micro.services.content
    environment:
      - Tenants_API=http://micro.services.tenants
      - Tenants_DB=Data Source=tcp:db;Initial Catalog=Tenants;User Id=sa;Password=Password123*;persist security info=False;packet size=4096
      - Content_API=http://micro.services.content
      - Content_DB=Data Source=tcp:db;Initial Catalog=Content;User Id=sa;Password=Password123*;persist security info=False;packet size=4096  
    volumes: 
      - ./tests:/tests
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/micro.acceptancetests.xml

  micro.services.tenants:
    image: micro.services.tenants
    build:
      context: .
      dockerfile: src/Micro.Services.Tenants/Dockerfile    
    depends_on:
      - db
      - logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=Tenants;User Id=sa;Password=Password123*;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5001:80"   
  
  micro.services.content:
    image: micro.services.content
    build:
      context: .
      dockerfile: src/Micro.Services.Content/Dockerfile    
    depends_on:
      - db
      - logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=Content;User Id=sa;Password=Password123*;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5002:80"   
      
  logs:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5003:80"

  db:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Password123*
      - ACCEPT_EULA=Y
    ports:
      - "51433:1433"