version: '3.4'

services:

  micro.integration.b:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=ServiceB;User Id=sa;Password=Pass@word;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5002:80"   
    entrypoint:
      - dotnet
      - test

  logs:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5003:80"
      
  db:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "51433:1433"