version: '3.4'

services:

  logs:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5003:80"

  db:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "51433:1433"