version: '3.4'

services:
  micro.services.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - TENANTS_URL=http://micro.services.tenants
      - CONTENT_URL=http://micro.services.content
      - SEQ_URL=http://logs
    ports:
      - "5000:80"   

  micro.services.tenants:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=Tenants;User Id=sa;Password=Password123;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5001:80"   
      
  micro.services.content:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=Content;User Id=sa;Password=Password123;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5002:80"   
      
  logs:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5003:80"
      
  db:
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "51433:1433"
