version: '3.4'

services:

  micro.services.gateway:
    image: micro.services.gateway
    build:
      context: .
      dockerfile: src/Micro.Services.Gateway/Dockerfile    
    depends_on:
      - micro.services.tenants
      - micro.services.content
      - logs

  micro.services.tenants:
    image: micro.services.tenants
    build:
      context: .
      dockerfile: src/Micro.Services.Tenants/Dockerfile    
    depends_on:
      - db
      - logs
  
  micro.services.content:
    image: micro.services.content
    build:
      context: .
      dockerfile: src/Micro.Services.Content/Dockerfile    
    depends_on:
      - db
      - logs
      
  logs:
    image: datalust/seq:latest

  db:
    image: microsoft/mssql-server-linux