version: '3.4'

services:
  micro.services.tenants.unittests:
    image: micro.services.tenants.unittests
    build:
      context: .
      dockerfile: src/Micro.Services.Tenants/Dockerfile   
      target: unit 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=Tenants;User Id=sa;Password=Password123*;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/micro.services.tenants.unittests.xml