version: '3.4'

services:
  micro.acceptance:
    environment:
      - SERVICE_A_API_ENDPOINT=http://micro.service.a
      - SERVICE_A_CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=ServiceA;User Id=sa;Password=Pass@word;persist security info=False;packet size=4096
      - SERVICE_B_API_ENDPOINT=http://micro.service.b
      - SERVICE_B_CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=ServiceB;User Id=sa;Password=Pass@word;persist security info=False;packet size=4096

  micro.service.a:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=ServiceA;User Id=sa;Password=Pass@word;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5001:80"   
      
  micro.service.b:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=ServiceB;User Id=sa;Password=Pass@word;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    ports:
      - "5002:80"   
      
  logs:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5003:80"
      
  db:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "51433:1433"