version: '3.4'

services:
  micro.acceptance:
    image: micro.acceptance
    build:
      context: .
      dockerfile: tests/Micro.AcceptanceTests/Dockerfile    
    depends_on:
      - micro.service.a
      - micro.service.b

  micro.service.a:
    image: micro.service.a
    build:
      context: .
      dockerfile: src/Micro.ServiceA/Dockerfile    
    depends_on:
      - db
      - logs
  
  micro.service.b:
    image: micro.service.b
    build:
      context: .
      dockerfile: src/Micro.ServiceB/Dockerfile    
    depends_on:
      - db
      - logs
      
  logs:
    image: datalust/seq:latest

  db:
    image: microsoft/mssql-server-linux