version: '3.4'

services:
  micro.integration.b:
    image: micro.integration.b
    build:
      context: .
      dockerfile: src/Micro.ServiceB/Dockerfile    
      target: integration 
    depends_on:
      - db
      - logs

  logs:
    image: datalust/seq:latest

  db:
    image: microsoft/mssql-server-linux