version: '3.4'

services:

  micro.services.tenants:
    image: peterkneale/micro.services.tenants:latest
    depends_on:
      - db
      - logs
  
  micro.services.content:
    image: peterkneale/micro.services.content:latest
    build:
      context: .
      dockerfile: src/Micro.Services.Content/Dockerfile    
    depends_on:
      - db
      - logs
      
  logs:
    image: datalust/seq:latest

  db:
    image: microsoft/mssql-server-linux