version: '3.4'

services:

  micro.services.content.unittests:
    image: micro.services.content.unittests
    build:
      context: .
      dockerfile: src/Micro.Services.Content/Dockerfile   
      target: unit 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CONNECTION_STRING=Data Source=tcp:db;Initial Catalog=Content;User Id=sa;Password=Password123*;persist security info=False;packet size=4096
      - SEQ_URL=http://logs
    volumes: 
      - ./tests:/tests
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/micro.services.content.unittests.xml